apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: desktop-office
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: desktop-office
    spec:
      containers:
      - name: desktop-office
        image: besn0847/desktop-office
        ports:
          - containerPort: 5900
---
apiVersion: v1
kind: Service
metadata:
  name: my-desktop-office
  labels:
    run : desktop-office
  namespace: default
spec:
  ports:
  - nodePort: 32415
    port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    app: desktop-office
  type: NodePort


